onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider {AEO SCC}
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/clk
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/rst
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/enable
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/busy
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/color_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/scc_addr_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/nextv_out
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/n_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/graph_info_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/rgraph_info_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/fw_addr_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/fw_count_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/bw_addr_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/bw_count_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/ae_id
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/nxtae_rx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/nxtae_rx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/prvae_rx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/prvae_rx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/nxtae_tx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/nxtae_tx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/prvae_tx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/prvae_tx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc0_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc0_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc0_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc0_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc0_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc0_req_flush
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc0_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc0_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc0_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc0_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc0_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc0_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc0_rsp_flush_cmplt
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc1_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc1_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc1_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc1_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc1_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc1_req_flush
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc1_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc1_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc1_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc1_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc1_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc1_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc1_rsp_flush_cmplt
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc2_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc2_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc2_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc2_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc2_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc2_req_flush
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc2_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc2_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc2_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc2_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc2_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc2_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc2_rsp_flush_cmplt
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc3_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc3_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc3_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc3_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc3_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc3_req_flush
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc3_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc3_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc3_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc3_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc3_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc3_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc3_rsp_flush_cmplt
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc4_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc4_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc4_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc4_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc4_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc4_req_flush
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc4_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc4_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc4_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc4_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc4_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc4_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc4_rsp_flush_cmplt
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc5_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc5_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc5_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc5_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc5_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc5_req_flush
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc5_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc5_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc5_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc5_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc5_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc5_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc5_rsp_flush_cmplt
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc6_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc6_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc6_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc6_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc6_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc6_req_flush
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc6_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc6_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc6_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc6_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc6_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc6_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc6_rsp_flush_cmplt
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc7_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc7_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc7_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc7_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc7_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc7_req_flush
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc7_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc7_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc7_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc7_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc7_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc7_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc7_rsp_flush_cmplt
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc8_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc8_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc8_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc8_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc8_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc8_req_flush
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc8_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc8_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc8_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc8_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc8_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc8_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc8_rsp_flush_cmplt
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc9_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc9_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc9_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc9_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc9_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc9_req_flush
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc9_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc9_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc9_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc9_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc9_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc9_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc9_rsp_flush_cmplt
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc10_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc10_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc10_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc10_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc10_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc10_req_flush
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc10_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc10_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc10_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc10_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc10_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc10_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc10_rsp_flush_cmplt
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc11_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc11_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc11_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc11_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc11_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc11_req_flush
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc11_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc11_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc11_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc11_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc11_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc11_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc11_rsp_flush_cmplt
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc12_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc12_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc12_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc12_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc12_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc12_req_flush
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc12_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc12_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc12_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc12_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc12_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc12_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc12_rsp_flush_cmplt
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc13_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc13_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc13_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc13_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc13_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc13_req_flush
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc13_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc13_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc13_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc13_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc13_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc13_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc13_rsp_flush_cmplt
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc14_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc14_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc14_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc14_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc14_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc14_req_flush
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc14_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc14_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc14_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc14_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc14_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc14_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc14_rsp_flush_cmplt
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc15_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc15_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc15_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc15_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc15_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc15_req_flush
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc15_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc15_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc15_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc15_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc15_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc15_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc15_rsp_flush_cmplt
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/n
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/color
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/scc_addr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/graph_info
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/rgraph_info
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/fw_addr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/fw_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/bw_addr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/bw_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/kernels_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/scc_state
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/kernel_enable
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/kernel_done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/kernel_busy
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc_flushed
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/kernel_tx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/kernel_tx_nextv
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/master_tx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/master_tx_nextv
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k2k_start
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0_rx_vld
add wave -noupdate -divider {AE0 details}
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/nxtae_rx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/prvae_rx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/nxtae_rx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/prvae_rx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/nxtae_rx_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/prvae_rx_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/nxtae_tx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/prvae_tx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/nxtae_tx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/prvae_tx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/nxtae_tx_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/prvae_tx_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/prvae_nd0_tx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/prvae_nd0_tx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/prvae_nd0_tx_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/nxtae_nd0_rx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/nxtae_nd0_rx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/nxtae_nd0_rx_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/reset_per
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/inst_caep
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/inst_aeg_idx
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/inst_val
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/inst_aeg_wr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/inst_aeg_rd
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/err_unimpl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/w_aeg
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_enable
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_busy
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/nq_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_enable
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_busy
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_nextv
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/r_ret_val
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/r_err_unimpl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/r_err_aegidx
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/r_ret_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/c_val_aegidx
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/r_reset
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/c_caep00
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/c_caep01
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/r_caep00
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/r_caep01
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/cy_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_en
add wave -noupdate -divider {AE1 SCC}
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/enable
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/busy
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/color_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/scc_addr_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/nextv_out
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/n_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/graph_info_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/rgraph_info_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/fw_addr_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/fw_count_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/bw_addr_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/bw_count_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/ae_id
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/nxtae_rx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/nxtae_rx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/prvae_rx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/prvae_rx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/nxtae_tx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/nxtae_tx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/prvae_tx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/prvae_tx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/n
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/color
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/scc_addr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/graph_info
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/rgraph_info
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/fw_addr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/fw_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/bw_addr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/bw_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/kernels_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/scc_state
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/kernel_enable
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/kernel_done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/kernel_busy
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/mc_flushed
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/kernel_tx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/kernel_tx_nextv
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/master_tx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/master_tx_nextv
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/k2k_start
add wave -noupdate -radix hexadecimal /testbench/cae_fpga1/ae_top/core/cae_pers/scc_inst/k0_rx_vld
add wave -noupdate -divider {AE2 SCC}
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/clk
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/rst
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/enable
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/busy
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/color_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/scc_addr_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/nextv_out
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/n_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/graph_info_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/rgraph_info_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/fw_addr_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/fw_count_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/bw_addr_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/bw_count_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/ae_id
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/nxtae_rx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/nxtae_rx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/prvae_rx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/prvae_rx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/nxtae_tx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/nxtae_tx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/prvae_tx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/prvae_tx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/n
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/color
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/scc_addr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/graph_info
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/rgraph_info
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/fw_addr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/fw_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/bw_addr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/bw_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/kernels_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/scc_state
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/kernel_enable
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/kernel_done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/kernel_busy
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/mc_flushed
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/kernel_tx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/kernel_tx_nextv
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/master_tx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/master_tx_nextv
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/k2k_start
add wave -noupdate -radix hexadecimal /testbench/cae_fpga2/ae_top/core/cae_pers/scc_inst/k0_rx_vld
add wave -noupdate -divider {AE3 SCC}
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/clk
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/rst
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/enable
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/busy
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/color_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/scc_addr_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/nextv_out
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/n_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/graph_info_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/rgraph_info_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/fw_addr_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/fw_count_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/bw_addr_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/bw_count_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/ae_id
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/nxtae_rx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/nxtae_rx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/prvae_rx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/prvae_rx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/nxtae_tx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/nxtae_tx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/prvae_tx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/prvae_tx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/n
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/color
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/scc_addr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/graph_info
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/rgraph_info
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/fw_addr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/fw_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/bw_addr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/bw_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/kernels_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/scc_state
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/kernel_enable
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/kernel_done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/kernel_busy
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/mc_flushed
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/kernel_tx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/kernel_tx_nextv
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/master_tx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/master_tx_nextv
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/k2k_start
add wave -noupdate -radix hexadecimal /testbench/cae_fpga3/ae_top/core/cae_pers/scc_inst/k0_rx_vld
add wave -noupdate -divider {AE0 BFS}
add wave -noupdate -divider {AE1 BFS}
add wave -noupdate -divider {AE2 BFS}
add wave -noupdate -divider {AE3 BFS}
add wave -noupdate -divider {Kernel 0}
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/clk
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/rst
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/enable
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/busy
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/kernel_id
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/ae_id
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/kernels_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/kernel_tx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/kernel_tx_nextv
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/kernel_rx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/kernel_rx_nextv
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/N
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/graph_info
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/rgraph_info
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/color
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/fw_queue
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/fw_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/bw_queue
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/bw_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/scc_results
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/mc_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/mc_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/mc_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/mc_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/mc_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/mc_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/mc_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/mc_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/mc_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/mc_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/mc_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/k_rst
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/started
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/info_addr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/rinfo_addr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/reach_queue
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/reach_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/found_nextv
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/kernel_state
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/master_done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_req_q_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_rsp_q_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_req_q_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_req_q_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_req_q_rd_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_req_q_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_req_q_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_req_q_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_req_q_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_req_q_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_rsp_q_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_rsp_q_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_rsp_q_rd_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_rsp_q_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_rsp_q_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_rsp_q_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_rsp_q_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_rsp_q_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_req_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_req_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_rsp_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_rsp_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_req_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_req_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_req_rd_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_req_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_req_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_req_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_req_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_req_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_req_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_req_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_req_rd_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_req_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_req_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_req_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_req_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_req_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_rsp_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_rsp_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_rsp_rd_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_rsp_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_rsp_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_rsp_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_rsp_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_rsp_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_rsp_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_rsp_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_rsp_rd_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_rsp_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_rsp_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_rsp_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_rsp_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_rsp_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_scc_addr_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_req_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_id_q_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_rsp_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_scc_addr_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_scc_addr_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_scc_addr_rd_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_scc_addr_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_scc_addr_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_scc_addr_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_scc_addr_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_scc_addr_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_req_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_req_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_req_rd_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_req_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_req_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_req_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_req_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_req_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_id_q_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_id_q_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_id_q_rd_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_id_q_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_id_q_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_id_q_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_id_q_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_id_q_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_rsp_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_rsp_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_rsp_rd_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_rsp_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_rsp_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_rsp_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_rsp_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_rsp_empty
add wave -noupdate -divider Master
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/enable
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/graph_info
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/color
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p1_req_q_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p1_req_q_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p1_req_q_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p1_req_q_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p1_rsp_q_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p1_rsp_q_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p1_rsp_q_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_scc_req_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_scc_req_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_scc_req_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_scc_req_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_scc_req_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_rinfo_req_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_rinfo_req_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_rinfo_req_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_rinfo_req_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_rinfo_req_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_scc_rsp_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_scc_rsp_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_scc_rsp_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_rinfo_rsp_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_rinfo_rsp_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_rinfo_rsp_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_scc_addr_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_scc_addr_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_scc_addr_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_scc_addr_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_info_req_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_info_req_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_info_req_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_info_req_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_id_q_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_id_q_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_id_q_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_id_q_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_info_rsp_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_info_rsp_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_info_rsp_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_info_rsp_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_info_rsp_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_info_rsp_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_info_rsp_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/mc_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/mc_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/mc_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/mc_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/mc_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/mc_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/mc_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/mc_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/mc_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/mc_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/mc_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/mux_state
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/done_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/saved_state
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/saved_addr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/saved_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/count
add wave -noupdate -divider {Process 1}
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1/enable
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1/kernel_id
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1/ae_id
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1/kernels_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1/reach_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1/reach_queue
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1/p1_done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1/p1_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1/p1_req_q_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1/p1_req_q_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1/p1_req_q_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1/p1_offset
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1/count
add wave -noupdate -divider {Process 2}
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2/enable
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2/p2_done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2/p2_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2/rgraph_info
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2/scc_results
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2/p1_done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2/p1_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2/p2_scc_req_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2/p2_scc_req_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2/p2_scc_req_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2/p2_rInfo_req_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2/p2_rInfo_req_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2/p2_rInfo_req_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2/mc_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2/mc_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2/mc_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2/count
add wave -noupdate -divider {Process 3}
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/enable
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p3_done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p3_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/graph_info
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/scc_results
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p2_done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p2_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p3_scc_addr_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p3_scc_addr_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p3_scc_addr_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p3_info_req_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p3_info_req_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p3_info_req_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p3_id_q_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p3_id_q_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p3_id_q_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p1_rsp_q_rd_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p1_rsp_q_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p1_rsp_q_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p1_rsp_q_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p1_rsp_q_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p2_scc_rsp_rd_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p2_scc_rsp_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p2_scc_rsp_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p2_scc_rsp_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p2_scc_rsp_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p2_rinfo_rsp_rd_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p2_rinfo_rsp_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p2_rinfo_rsp_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p2_rinfo_rsp_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p2_rinfo_rsp_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/count_1
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/count_2
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {71322 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {2778722 ps}
