onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider {AEO SCC}
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/clk
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/rst
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/enable
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/r_rst
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/r_enable
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/busy
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/color_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/scc_addr_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/nextv_out
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/n_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/graph_info_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/rgraph_info_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/fw_addr_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/fw_count_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/bw_addr_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/bw_count_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/ae_id
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/nxtae_rx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/nxtae_rx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/prvae_rx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/prvae_rx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/nxtae_tx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/nxtae_tx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/prvae_tx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/prvae_tx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc0_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc0_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc0_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc0_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc0_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc0_req_flush
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc0_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc0_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc0_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc0_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc0_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc0_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc0_rsp_flush_cmplt
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc1_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc1_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc1_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc1_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc1_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc1_req_flush
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc1_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc1_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc1_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc1_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc1_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc1_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc1_rsp_flush_cmplt
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc2_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc2_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc2_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc2_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc2_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc2_req_flush
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc2_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc2_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc2_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc2_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc2_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc2_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc2_rsp_flush_cmplt
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc3_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc3_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc3_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc3_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc3_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc3_req_flush
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc3_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc3_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc3_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc3_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc3_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc3_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc3_rsp_flush_cmplt
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc4_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc4_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc4_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc4_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc4_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc4_req_flush
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc4_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc4_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc4_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc4_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc4_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc4_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc4_rsp_flush_cmplt
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc5_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc5_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc5_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc5_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc5_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc5_req_flush
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc5_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc5_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc5_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc5_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc5_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc5_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc5_rsp_flush_cmplt
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc6_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc6_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc6_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc6_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc6_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc6_req_flush
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc6_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc6_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc6_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc6_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc6_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc6_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc6_rsp_flush_cmplt
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc7_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc7_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc7_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc7_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc7_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc7_req_flush
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc7_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc7_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc7_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc7_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc7_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc7_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc7_rsp_flush_cmplt
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc8_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc8_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc8_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc8_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc8_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc8_req_flush
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc8_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc8_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc8_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc8_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc8_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc8_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc8_rsp_flush_cmplt
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc9_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc9_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc9_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc9_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc9_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc9_req_flush
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc9_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc9_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc9_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc9_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc9_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc9_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc9_rsp_flush_cmplt
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc10_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc10_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc10_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc10_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc10_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc10_req_flush
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc10_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc10_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc10_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc10_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc10_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc10_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc10_rsp_flush_cmplt
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc11_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc11_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc11_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc11_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc11_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc11_req_flush
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc11_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc11_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc11_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc11_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc11_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc11_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc11_rsp_flush_cmplt
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc12_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc12_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc12_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc12_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc12_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc12_req_flush
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc12_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc12_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc12_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc12_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc12_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc12_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc12_rsp_flush_cmplt
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc13_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc13_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc13_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc13_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc13_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc13_req_flush
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc13_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc13_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc13_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc13_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc13_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc13_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc13_rsp_flush_cmplt
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc14_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc14_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc14_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc14_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc14_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc14_req_flush
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc14_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc14_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc14_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc14_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc14_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc14_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc14_rsp_flush_cmplt
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc15_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc15_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc15_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc15_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc15_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc15_req_flush
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc15_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc15_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc15_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc15_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc15_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc15_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/mc15_rsp_flush_cmplt
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/n
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/color
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/scc_addr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/graph_info
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/rgraph_info
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/fw_addr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/fw_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/bw_addr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/bw_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/kernels_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/scc_state
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/kernels_enable
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/kernels_done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/kernels_busy
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/kernel_tx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/kernel_tx_nextv
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/nxtk_rst
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/nxtk_enable
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/nextk_busy
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/nextk_done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/nxtk_N
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/nxtk_graph_info
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/nxtk_rgraph_info
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/nxtk_color
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/nxtk_fw_queue
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/nxtk_fw_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/nxtk_bw_queue
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/nxtk_bw_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/nxtk_scc_results
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/master_tx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/master_tx_nextv
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k2k_start
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0_rx_vld
add wave -noupdate -divider {AE0 CAE_PERS}
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/NA
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/NB
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/clk_csr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/clk
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/clk2x
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/i_reset
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/i_csr_reset_n
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/i_aeid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/ppll_reset
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/ppll_locked
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/clk_per
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/cae_inst
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/cae_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/cae_inst_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/cae_aeg_cnt
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/cae_exception
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/cae_ret_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/cae_ret_data_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/cae_idle
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/cae_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/nxtae_rx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/prvae_rx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/nxtae_rx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/prvae_rx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/nxtae_rx_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/prvae_rx_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/nxtae_tx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/prvae_tx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/nxtae_tx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/prvae_tx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/nxtae_tx_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/prvae_tx_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/prvae_nd0_tx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/prvae_nd0_tx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/prvae_nd0_tx_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/nxtae_nd0_rx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/nxtae_nd0_rx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/nxtae_nd0_rx_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/prvae_nd1_tx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/prvae_nd1_tx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/prvae_nd1_tx_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/nxtae_nd1_rx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/nxtae_nd1_rx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/nxtae_nd1_rx_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/cae_ring_ctl_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/cae_ring_data_in
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/cae_ring_ctl_out
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/cae_ring_data_out
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/csr_31_31_intlv_dis
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/reset_per
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/inst_caep
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/inst_aeg_idx
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/inst_val
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/inst_aeg_wr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/inst_aeg_rd
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/err_unimpl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/w_aeg
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_enable
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_busy
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/nq_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_enable
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_busy
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_nextv
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/r_ret_val
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/r_err_unimpl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/r_err_aegidx
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/r_ret_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/c_val_aegidx
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/r_reset
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/c_caep00
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/c_caep01
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/r_caep00
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/r_caep01
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/full_reset
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/cy_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/cy_n
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/non_zeros
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/graphData
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/graphInfo
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/queue1_address
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/queue2_address
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/current_level
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/cq_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/reach_queue
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_results
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_graphInfo
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_rgraphInfo
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_fw_addr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_fw_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_bw_addr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_bw_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_N
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_color
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_nxtae_tx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_nxtae_tx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_prvae_tx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_prvae_tx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/r_nxtae_tx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/r_nxtae_tx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/r_prvae_tx_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/r_prvae_tx_vld
add wave -noupdate -divider {Kernel 0}
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/clk
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/rst
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/enable
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/busy
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/kernel_id
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/ae_id
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/kernels_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/kernel_tx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/kernel_tx_nextv
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/kernel_rx_vld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/kernel_rx_nextv
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/N
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/graph_info
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/rgraph_info
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/color
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/fw_queue
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/fw_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/bw_queue
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/bw_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/scc_results
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/nxtk_rst
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/nxtk_enable
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/nextk_busy
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/nextk_done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/nxtk_N
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/nxtk_graph_info
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/nxtk_rgraph_info
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/nxtk_color
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/nxtk_fw_queue
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/nxtk_fw_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/nxtk_bw_queue
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/nxtk_bw_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/nxtk_scc_results
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/mc_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/mc_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/mc_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/mc_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/mc_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/mc_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/mc_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/mc_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/mc_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/mc_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/mc_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/k_rst
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/k_busy
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/k_done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/started
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/info_addr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/rinfo_addr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/reach_queue
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/reach_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/found_nextv
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/nextk_done_cache
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/kernel_state
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/master_done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_req_q_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_rsp_q_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_req_q_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_req_q_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_req_q_rd_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_req_q_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_req_q_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_req_q_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_req_q_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_req_q_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_rsp_q_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_rsp_q_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_rsp_q_rd_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_rsp_q_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_rsp_q_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_rsp_q_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_rsp_q_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p1_rsp_q_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_req_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_req_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_rsp_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_rsp_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_req_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_req_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_req_rd_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_req_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_req_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_req_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_req_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_req_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_req_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_req_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_req_rd_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_req_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_req_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_req_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_req_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_req_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_rsp_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_rsp_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_rsp_rd_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_rsp_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_rsp_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_rsp_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_rsp_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_scc_rsp_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_rsp_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_rsp_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_rsp_rd_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_rsp_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_rsp_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_rsp_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_rsp_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p2_rinfo_rsp_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_scc_addr_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_req_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_id_q_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_rsp_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_scc_addr_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_scc_addr_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_scc_addr_rd_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_scc_addr_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_scc_addr_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_scc_addr_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_scc_addr_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_scc_addr_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_req_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_req_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_req_rd_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_req_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_req_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_req_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_req_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_req_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_id_q_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_id_q_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_id_q_rd_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_id_q_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_id_q_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_id_q_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_id_q_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_id_q_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_rsp_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_rsp_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_rsp_rd_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_rsp_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_rsp_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_rsp_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_rsp_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3_info_rsp_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/queues_mask1
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/queues_mask2
add wave -noupdate -divider {K0 Master}
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/clk
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/rst
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/enable
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/graph_info
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/color
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p1_req_q_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p1_req_q_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p1_req_q_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p1_req_q_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p1_rsp_q_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p1_rsp_q_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p1_rsp_q_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_scc_req_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_scc_req_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_scc_req_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_scc_req_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_scc_req_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_rinfo_req_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_rinfo_req_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_rinfo_req_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_rinfo_req_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_rinfo_req_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_scc_rsp_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_scc_rsp_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_scc_rsp_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_rinfo_rsp_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_rinfo_rsp_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_rinfo_rsp_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_scc_addr_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_scc_addr_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_scc_addr_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_scc_addr_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_info_req_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_info_req_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_info_req_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_info_req_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_id_q_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_id_q_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_id_q_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_id_q_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_info_rsp_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_info_rsp_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_info_rsp_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_info_rsp_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_info_rsp_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_info_rsp_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p3_info_rsp_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/mc_req_ld
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/mc_req_st
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/mc_req_size
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/mc_req_vaddr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/mc_req_wrd_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/mc_rd_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/mc_wr_rq_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/mc_rsp_push
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/mc_rsp_stall
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/mc_rsp_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/mc_rsp_rdctl
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/mux_state
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/done_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/saved_state
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/saved_addr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/saved_data
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_q_alt
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_scc_rsp_wr_en_temp
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_scc_rsp_din_temp
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_rinfo_rsp_wr_en_temp
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p_master/p2_rinfo_rsp_din_temp
add wave -noupdate -divider P3
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/clk
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/rst
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/enable
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p3_done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p3_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/graph_info
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/scc_results
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p2_done
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p2_count
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p3_scc_addr_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p3_scc_addr_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p3_scc_addr_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p3_info_req_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p3_info_req_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p3_info_req_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p3_id_q_almost_full
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p3_id_q_wr_en
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p3_id_q_din
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p1_rsp_q_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p1_rsp_q_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p1_rsp_q_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p1_rsp_q_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p2_scc_rsp_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p2_scc_rsp_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p2_scc_rsp_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p2_scc_rsp_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p2_rinfo_rsp_rd_enb
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p2_rinfo_rsp_dout
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p2_rinfo_rsp_valid
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/p2_rinfo_rsp_empty
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/count_1
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/count_2
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/u_idx8
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/u_scc_addr
add wave -noupdate -radix hexadecimal /testbench/cae_fpga0/ae_top/core/cae_pers/scc_inst/k0/p3/u_graph_info
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {584 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {1 ns}
