onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider {Master 0}
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/clk
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/rst
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/enable
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/busy
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/done
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/started
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/current_level
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/kernel_rx_vld
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/wr_offset
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/wr_reserved_space
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/wr_used_space
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/graphInfo
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/nq_address
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/reach_queue
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/mc_req_ld
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/mc_req_st
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/mc_req_size
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/mc_req_vaddr
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/mc_req_wrd_rdctl
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/mc_rd_rq_stall
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/mc_wr_rq_stall
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/p1_req_q_rd_enb
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/p1_req_q_dout
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/p1_req_q_valid
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/p1_req_q_empty
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/p2_req_q_rd_enb
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/p2_req_q_dout
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/p2_req_q_valid
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/p2_req_q_empty
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/p3_req_q_rd_enb
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/p3_req_q_dout
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/p3_req_q_valid
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/p3_req_q_empty
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/p4_done
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/p4_addr_q_rd_enb
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/p4_addr_q_dout
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/p4_addr_q_valid
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/p4_addr_q_empty
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/p4_info_q_rd_enb
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/p4_info_q_dout
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/p4_info_q_valid
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/p4_info_q_empty
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/state
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/mux_state
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/saved_state
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/saved_addr
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/saved_data
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/used_space
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/local_offset
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/pause_p4
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/done_count
add wave -noupdate -divider {Kernel 0}
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p0/p2_req_count_debug
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/clk
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/rst
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/enable
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/busy
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/done
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/kernel_id
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/ae_id
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/kernels_count
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/current_level
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/cq_count
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/kernel_tx_done
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/kernel_tx_vld
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/kernel_tx_count
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/kernel_rx_done
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/kernel_rx_vld
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/kernel_rx_count
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/graphData
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/graphInfo
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/cq_address
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/nq_address
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/reach_queue
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/mc_req_ld
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/mc_req_st
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/mc_req_size
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/mc_req_vaddr
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/mc_req_wrd_rdctl
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/mc_rd_rq_stall
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/mc_wr_rq_stall
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/mc_rsp_push
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/mc_rsp_stall
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/mc_rsp_data
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/mc_rsp_rdctl
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/k_rst
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/started
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/wr_offset
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/wr_demand_count
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/wr_reserved_space
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/wr_used_space
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/out_done
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/out_kernel_tx_vld
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p1_done
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p1_count
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p1_offset
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p1_req_q_almost_full
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p1_req_q_wr_en
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p1_req_q_rd_enb
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p1_req_q_rd_en
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p1_req_q_din
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p1_req_q_dout
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p1_req_q_valid
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p1_req_q_full
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p1_req_q_empty
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p1_rsp_q_almost_full
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p1_rsp_q_wr_en
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p1_rsp_q_rd_enb
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p1_rsp_q_rd_en
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p1_rsp_q_din
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p1_rsp_q_dout
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p1_rsp_q_valid
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p1_rsp_q_full
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p1_rsp_q_empty
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p2_done
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p2_busy
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p2_count_1
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p2_count_2
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p2_req_q_almost_full
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p2_req_q_wr_en
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p2_req_q_rd_enb
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p2_req_q_rd_en
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p2_req_q_din
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p2_req_q_dout
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p2_req_q_valid
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p2_req_q_full
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p2_req_q_empty
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p2_rsp_q_almost_full
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p2_rsp_q_wr_en
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p2_rsp_q_rd_enb
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p2_rsp_q_rd_en
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p2_rsp_q_din
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p2_rsp_q_dout
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p2_rsp_q_valid
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p2_rsp_q_full
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p2_rsp_q_empty
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p3_done
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p3_count
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p3_req_q_almost_full
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p3_req_q_wr_en
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p3_req_q_rd_enb
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p3_req_q_rd_en
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p3_req_q_din
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p3_req_q_dout
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p3_req_q_valid
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p3_req_q_full
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p3_req_q_empty
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p3_rsp_q_almost_full
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p3_rsp_q_wr_en
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p3_rsp_q_rd_enb
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p3_rsp_q_rd_en
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p3_rsp_q_din
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p3_rsp_q_dout
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p3_rsp_q_valid
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p3_rsp_q_full
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p3_rsp_q_empty
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p4_done
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p4_count
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p4_state
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p4_addr_q_almost_full
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p4_addr_q_wr_en
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p4_addr_q_rd_enb
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p4_addr_q_rd_en
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p4_addr_q_din
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p4_addr_q_dout
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p4_addr_q_valid
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p4_addr_q_full
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p4_addr_q_empty
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p4_info_q_almost_full
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p4_info_q_wr_en
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p4_info_q_rd_enb
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p4_info_q_rd_en
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p4_info_q_din
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p4_info_q_dout
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p4_info_q_valid
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p4_info_q_full
add wave -noupdate -divider {CAE Pers}
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_inst/k0/p4_info_q_empty
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/NUM_FPS
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/SIDEBAND_FENCE
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/MC_STRONG_ORDER
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/MC_READ_ORDER
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/MC_WR_CMP_IF
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/CLK_PERS_RATIO
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/RATIO
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/CNY_PDK_PLATFORM
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/MC_XBAR
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/MC_XB_DEPTH
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/MC_XBAR_INTLV
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/AE_AE_IF
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/PART_NUMBER
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/VERSION_NUMBER
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/NA
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/NB
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/clk_csr
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/clk
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/clk2x
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/i_reset
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/i_csr_reset_n
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/i_aeid
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/ppll_reset
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/ppll_locked
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/clk_per
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cae_inst
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cae_data
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cae_inst_vld
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cae_aeg_cnt
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cae_exception
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cae_ret_data
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cae_ret_data_vld
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cae_idle
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cae_stall
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/reset_per
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/inst_caep
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/inst_aeg_idx
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/inst_val
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/inst_aeg_wr
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/inst_aeg_rd
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/err_unimpl
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/w_aeg
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_enable
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_busy
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cygraph_done
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/nq_count
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/r_ret_val
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/r_err_unimpl
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/r_err_aegidx
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/r_ret_data
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/c_val_aegidx
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/r_reset
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/c_caep00
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/r_caep00
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cy_en
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/prvae_nd1_tx_data
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/prvae_nd1_tx_vld
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/nxtae_nd1_rx_stall
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cy_n
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/non_zeros
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/graphData
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/graphInfo
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/queue1_address
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/queue2_address
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/current_level
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/cq_count
add wave -noupdate /testbench/cae_fpga0/ae_top/core/cae_pers/reach_queue
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {1 ns}
